apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kafka-connector-watchdog.fullname" . }}
  labels:
    {{- include "kafka-connector-watchdog.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-connector-watchdog.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      template:
        spec:
            {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            serviceAccountName: {{ include "kafka-connector-watchdog.serviceAccountName" . }}
            {{- with .Values.podSecurityContext }}
            securityContext:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            restartPolicy: {{ .Values.job.restartPolicy }}
            containers:
            - name: {{ .Chart.Name }}
                {{- with .Values.securityContext }}
                securityContext:
                {{- toYaml . | nindent 12 }}
                {{- end }}
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                {{- with .Values.resources }}
                resources:
                {{- toYaml . | nindent 12 }}
                {{- end }}
                {{- with .Values.volumeMounts }}
                volumeMounts:
                {{- toYaml . | nindent 12 }}
                {{- end }}
                {{- with .Values.job.env }}
                env:
                {{ toYaml . | nindent 10 }}
                {{- end }}
                {{- with .Values.job.envFrom }}
                envFrom:
                {{ toYaml . | nindent 10 }}
                {{- end }}
                {{- with .Values.job.command }}
                command:
                {{ toYaml . | nindent 10 }}
                {{- end }}
                    {{- with .Values.job.args }}
                args:
                {{ toYaml . | nindent 10 }}
                {{- end }}
            {{- with .Values.volumes }}
            volumes:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
                {{- toYaml . | nindent 8 }}
            {{- end }}
